# Artificial Neural Network

In [1]:
# importing required packages
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
# load dataset
df = pd.read_csv('Churn_Modelling.csv')
df.shape

(10000, 14)

In [3]:
# view top 5 rows
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [5]:
# discard "RowNumber", "CustomerId" and "Surname" features
X = df.iloc[:, 3:-1].values
y = df.iloc[:, -1].values

In [8]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [9]:
print(y)

[1 0 1 ... 1 1 0]


### Handle Categorical Features

In [10]:
# Label Encoding the "Gender" column
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [11]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [12]:
# One Hot Encoding the "Geography" column
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [13]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [14]:
# view first row
X[0]

array([1.0, 0.0, 0.0, 619, 0, 42, 2, 0.0, 1, 1, 1, 101348.88],
      dtype=object)

### Perform Train Test Split

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Perform Feature Scaling

In [16]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

### Building the ANN

In [17]:
# Initializing the ANN
ann = tf.keras.models.Sequential()

# Adding the input layer and the first hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

# Adding the second hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

# Adding the output layer
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Compiling the ANN
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [19]:
# Training the ANN on the Training set
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 3s 3ms/step - loss: 0.5574 - accuracy: 0.7150
Epoch 2/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4497 - accuracy: 0.7958
Epoch 3/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4347 - accuracy: 0.7969
Epoch 4/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4229 - accuracy: 0.8025
Epoch 5/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4086 - accuracy: 0.8169
Epoch 6/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3906 - accuracy: 0.8393
Epoch 7/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3747 - accuracy: 0.8494
Epoch 8/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3646 - accuracy: 0.8519
Epoch 9/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3584 - accuracy: 0.8536
Epoch 10/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3541 - accura

250/250 [==============================] - 1s 2ms/step - loss: 0.3339 - accuracy: 0.8630
Epoch 82/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3336 - accuracy: 0.8634
Epoch 83/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3334 - accuracy: 0.8637
Epoch 84/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3332 - accuracy: 0.8639
Epoch 85/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3327 - accuracy: 0.8636
Epoch 86/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3333 - accuracy: 0.8625
Epoch 87/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3332 - accuracy: 0.8651
Epoch 88/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3330 - accuracy: 0.8658
Epoch 89/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3331 - accuracy: 0.8630
Epoch 90/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3328 - accuracy: 

Use our ANN model to predict if the customer with the following informations will leave the bank: 

|Feature| Value|
| --- | --- |
|Geography| France|
|Credit Score| 600|
|Gender| Male|
|Age| 40 years old|
|Tenure| 3 years|
|Balance| \$ 60000|
|Number of Products| 2|
|Does this customer have a credit card ?| Yes|
|Is this customer an Active Member| Yes|
|Estimated Salary| \$ 50000|

So, should we say goodbye to that customer ?

In [20]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

[[False]]


### Predicting the Test set results

In [22]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [23]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1505   90]
 [ 190  215]]


0.86